services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install -g pm2 && npm install && npm run build && pm2-runtime start npm -- start"
    env_file:
      - .env.production
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=altokerprod
      - POSTGRES_PASSWORD=gVAifbImg7Eu01XU
      - POSTGRES_DB=altoke_spa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: